config/routes.rb
Rails.application.routes.draw do
  resources :cities
  resources :information
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/information.rb
class Information < ApplicationRecord
end

app/controllers/information_controller.rb
#!/usr/bin/env ruby
# encoding: utf-8

require "bunny"

class InformationController < ApplicationController

  before_action :authenticate_user!

  # GET /information
  # GET /information.json
  def index
    @information = Information.all
    @city = City.find_by_user_id(current_user.id)
  end

  # GET /information/new
  def new
    @information = Information.new
  end

  # POST /information
  # POST /information.json
  def create
    @information = Information.new(information_params)
    @information.producer = current_user.id
    @city = City.find_by_user_id(current_user.id)

    @info = current_user.email + " says " + @information.content

    respond_to do |format|
      if @information.save

        conn = Bunny.new(:automatically_recover => false)
        conn.start

        ch       = conn.create_channel
        x        = ch.topic("topic_logs")
        severity = ARGV.shift || @city.name
        msg      = ARGV.empty? ? "Hello World!" : ARGV.join(" ")

        x.publish(@info, :routing_key => severity)

        conn.close

        format.html { redirect_to information_index_path, notice: 'Information was successfully created.' }
        format.json { render :show, status: :created, location: information_index_path }
      else
        format.html { render :new }
        format.json { render json: @information.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_information
      @information = Information.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def information_params
      params.require(:information).permit(:content)
    end
end

app/helpers/information_helper.rb
module InformationHelper
end

app/views/information/_form.html.erb
<%= form_for(information) do |f| %>
  <% if information.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(information.errors.count, "error") %> prohibited this information from being saved:</h2>

      <ul>
      <% information.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>

  <br>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/information/edit.html.erb
<h1>Editing Information</h1>

<%= render 'form', information: @information %>

<%= link_to 'Show', @information %> |
<%= link_to 'Back', information_index_path %>

app/views/information/index.html.erb
<h1>Information</h1>

<% if @city!=nil %>

  <p> My City: <%= @city.name %> </p>

<% end %>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @information.each do |information| %>
      <tr>
        <% if information.producer==current_user.id %>
          <td><%= information.content %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to "New Information", new_information_path, class: 'btn btn-default' %>

app/views/information/new.html.erb
<h3>New Send</h3>

<br>

<%= render 'form', information: @information %>

app/views/information/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @information.content %>
</p>

<%= link_to 'Edit', edit_information_path(@information) %> |
<%= link_to 'Back', information_index_path %>